config/routes.rb
Rails.application.routes.draw do

  resources :posts

  resources :search do
    collection do
      get 'search_word'
    end
  end

  resources :category_news

  resources :dictionaries

  resources :words do
    collection do
      get 'words_in_day'
      get 'words_in_rss'
      get 'charts'
    end
  end

  resources :frequencies
  resources :rsses

  resources :yandex_news do
    collection do
      get 'news_category' 
    end
  end

  match "/404" => "errors#error_404", via: [ :get, :post, :patch, :delete ]
  match "/500" => "errors#error_500", via: [ :get, :post, :patch, :delete ]
  root 'search#index'

end

app/models/yandex_news.rb
class YandexNews < ActiveRecord::Base
end

app/controllers/yandex_news_controller.rb
class YandexNewsController < ApplicationController
  before_action :set_yandex_news, only: [:show, :edit, :update, :destroy]

  # GET /yandex_news
  # GET /yandex_news.json
  def index
    @rating_words = Word.where(date: Time.now.beginning_of_day).order("count DESC").first(10)
    @categories = CategoryNews.all.map{|t| {t.title=>t.rsses.map{|e| {e.title=>e.rss_index}}}}
    @res_main_rus = two_arrays_to_one("http://news.yandex.ru/index.rss")
    @res_main_ua = two_arrays_to_one("http://news.yandex.ua/index.rss")
  end

  def news_category
    @doc_arr = {}
    @doc_arr = two_arrays_to_one(params[:url])
    render layout: false
  end

  #  GET /yandex_news/1
  # GET /yandex_news/1.json
  def show
  end

  # GET /yandex_news/new
  def new
    @yandex_news = YandexNews.new
  end

  # GET /yandex_news/1/edit
  def edit
  end
#
  # POST /yandex_news
  # POST /yandex_news.json
  def create
    @yandex_news = YandexNews.new(yandex_news_params)

    respond_to do |format|
      if @yandex_news.save
        format.html { redirect_to @yandex_news, notice: 'Yandex news was successfully created.' }
        format.json { render :show, status: :created, location: @yandex_news }
      else
        format.html { render :new }
        format.json { render json: @yandex_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yandex_news/1
  # PATCH/PUT /yandex_news/1.json
  def update
    respond_to do |format|
      if @yandex_news.update(yandex_news_params)
        format.html { redirect_to @yandex_news, notice: 'Yandex news was successfully updated.' }
        format.json { render :show, status: :ok, location: @yandex_news }
      else
        format.html { render :edit }
        format.json { render json: @yandex_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yandex_news/1
  # DELETE /yandex_news/1.json
  def destroy
    @yandex_news.destroy
    respond_to do |format|
      format.html { redirect_to yandex_news_index_url, notice: 'Yandex news was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yandex_news
      @yandex_news = YandexNews.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yandex_news_params
      params[:yandex_news]
    end
end

app/helpers/yandex_news_helper.rb
module YandexNewsHelper
end

app/views/yandex_news/_form.html.erb
<%= form_for(@yandex_news) do |f| %>
  <% if @yandex_news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yandex_news.errors.count, "error") %> prohibited this yandex_news from being saved:</h2>

      <ul>
      <% @yandex_news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/yandex_news/edit.html.erb
<h1>Editing yandex_news</h1>

<%= render 'form' %>

<%= link_to 'Show', @yandex_news %> |
<%= link_to 'Back', yandex_news_index_path %>

app/views/yandex_news/index.html.haml
%h1.header_title Обзор новостей
%h2 Топ 10 самых упоминаемых слов за сегодня
%ol
  -@rating_words.each do |word|
    %li.rating_on_main
      =word.title
      =word.count
=link_to "Подробнее", words_path, :class => "word_path_more"
%hr
.rus_news
  %h2.main_news Главные новости(РФ)
  -@res_main_rus.each do |title,url|
    .main_news_title=link_to title, url, :target => "_blank", :rel => "nofollow"
.ua_news
  %h2.main_news Главные новости(Украина)
  -@res_main_ua.each do |title,url|
    .main_news_title=link_to title, url, :target => "_blank", :rel => "nofollow"
.other_news
  %hr
  %h2.mail_news Остальные разделы:
  -@categories.each do |title_c|
    -title_c.each do |title_t,url_c|
      =link_to title_t, "javascript:void(0)", :class=>"category_news"
      .news_index{style: "display:none"}
        -url_c.each do |title_u|
          -title_u.each do |title,url|
            =link_to title, "javascript:void(0)",:class=>"news",:data=>{:url=>url}
            .news_content{:class=>"news_content_#{title}"}
.text_container    

app/views/yandex_news/new.html.erb
<h1>New yandex_news</h1>

<%= render 'form' %>

<%= link_to 'Back', yandex_news_index_path %>

app/views/yandex_news/news_category.html.haml
-if !@doc_arr.empty?
  -@doc_arr.each do |title,url|
    .event_news=link_to title, url, :target => "_blank", :rel => "nofollow"
-else
  .event_news В данный момент ничего не найдено 

app/views/yandex_news/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_yandex_news_path(@yandex_news) %> |
<%= link_to 'Back', yandex_news_index_path %>