config/routes.rb
Rails.application.routes.draw do

  resources :posts

  resources :search do
    collection do
      get 'search_word'
    end
  end

  resources :category_news

  resources :dictionaries

  resources :words do
    collection do
      get 'words_in_day'
      get 'words_in_rss'
      get 'charts'
    end
  end

  resources :frequencies
  resources :rsses

  resources :yandex_news do
    collection do
      get 'news_category' 
    end
  end

  match "/404" => "errors#error_404", via: [ :get, :post, :patch, :delete ]
  match "/500" => "errors#error_500", via: [ :get, :post, :patch, :delete ]
  root 'search#index'

end

app/models/frequency.rb
class Frequency < ActiveRecord::Base
  has_and_belongs_to_many :words
end

app/controllers/frequencies_controller.rb
class FrequenciesController < ApplicationController
  before_action :set_frequency, only: [:show, :edit, :update, :destroy]

  # GET /frequencies
  # GET /frequencies.json
  def index
    @frequencies = Frequency.all
  end

  # GET /frequencies/1
  # GET /frequencies/1.json
  def show
  end

  # GET /frequencies/new
  def new
    @frequency = Frequency.new
  end

  # GET /frequencies/1/edit
  def edit
  end

  # POST /frequencies
  # POST /frequencies.json
  def create
    @frequency = Frequency.new(frequency_params)

    respond_to do |format|
      if @frequency.save
        format.html { redirect_to @frequency, notice: 'Frequency was successfully created.' }
        format.json { render :show, status: :created, location: @frequency }
      else
        format.html { render :new }
        format.json { render json: @frequency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frequencies/1
  # PATCH/PUT /frequencies/1.json
  def update
    respond_to do |format|
      if @frequency.update(frequency_params)
        format.html { redirect_to @frequency, notice: 'Frequency was successfully updated.' }
        format.json { render :show, status: :ok, location: @frequency }
      else
        format.html { render :edit }
        format.json { render json: @frequency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frequencies/1
  # DELETE /frequencies/1.json
  def destroy
    @frequency.destroy
    respond_to do |format|
      format.html { redirect_to frequencies_url, notice: 'Frequency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frequency
      @frequency = Frequency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frequency_params
      params.require(:frequency).permit(:date, :title, :count)
    end
end

app/helpers/frequencies_helper.rb
module FrequenciesHelper
end

app/views/frequencies/_form.html.haml
= form_for @frequency do |f|
  - if @frequency.errors.any?
    #error_explanation
      %h2= "#{pluralize(@frequency.errors.count, "error")} prohibited this frequency from being saved:"
      %ul
        - @frequency.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :date
    = f.datetime_select :date
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :count
    = f.number_field :count
  .actions
    = f.submit 'Save'

app/views/frequencies/edit.html.haml
%h1 Editing frequency

= render 'form'

= link_to 'Show', @frequency
\|
= link_to 'Back', frequencies_path

app/views/frequencies/index.html.haml
%h1 Listing frequencies

%table
  %tr
    %th Date
    %th Title
    %th Count
    %th
    %th
    %th

  - @frequencies.each do |frequency|
    %tr
      %td= frequency.date
      %td= frequency.title
      %td= frequency.count
      %td= link_to 'Show', frequency
      %td= link_to 'Edit', edit_frequency_path(frequency)
      %td= link_to 'Destroy', frequency, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Frequency', new_frequency_path

app/views/frequencies/new.html.haml
%h1 New frequency

= render 'form'

= link_to 'Back', frequencies_path

app/views/frequencies/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @frequency.date
%p
  %b Title:
  = @frequency.title
%p
  %b Count:
  = @frequency.count

= link_to 'Edit', edit_frequency_path(@frequency)
\|
= link_to 'Back', frequencies_path