config/routes.rb
Rails.application.routes.draw do

  resources :posts

  resources :search do
    collection do
      get 'search_word'
    end
  end

  resources :category_news

  resources :dictionaries

  resources :words do
    collection do
      get 'words_in_day'
      get 'words_in_rss'
      get 'charts'
    end
  end

  resources :frequencies
  resources :rsses

  resources :yandex_news do
    collection do
      get 'news_category' 
    end
  end

  match "/404" => "errors#error_404", via: [ :get, :post, :patch, :delete ]
  match "/500" => "errors#error_500", via: [ :get, :post, :patch, :delete ]
  root 'search#index'

end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /dictionaries
  # GET /dictionaries.json
  def index
    @dictionaries = Dictionary.all
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @dictionary }
      else
        format.html { render :new }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  # PATCH/PUT /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to dictionaries_url, notice: 'Dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictionary
      @dictionary = Dictionary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dictionary_params
      params.require(:dictionary).permit(:value)
    end
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/_form.html.haml
= form_for @dictionary do |f|
  - if @dictionary.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dictionary.errors.count, "error")} prohibited this dictionary from being saved:"
      %ul
        - @dictionary.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :value
    = f.text_field :value
  .actions
    = f.submit 'Save'

app/views/dictionaries/edit.html.haml
%h1 Editing dictionary

= render 'form'

= link_to 'Show', @dictionary
\|
= link_to 'Back', dictionaries_path

app/views/dictionaries/index.html.haml
%h1 Listing dictionaries

%table
  %tr
    %th Value
    %th
    %th
    %th

  - @dictionaries.each do |dictionary|
    %tr
      %td= dictionary.value
      %td= link_to 'Show', dictionary
      %td= link_to 'Edit', edit_dictionary_path(dictionary)
      %td= link_to 'Destroy', dictionary, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Dictionary', new_dictionary_path

app/views/dictionaries/new.html.haml
%h1 New dictionary

= render 'form'

= link_to 'Back', dictionaries_path

app/views/dictionaries/show.html.haml
%p#notice= notice

%p
  %b Value:
  = @dictionary.value

= link_to 'Edit', edit_dictionary_path(@dictionary)
\|
= link_to 'Back', dictionaries_path