config/routes.rb
Rails.application.routes.draw do

  resources :posts

  resources :search do
    collection do
      get 'search_word'
    end
  end

  resources :category_news

  resources :dictionaries

  resources :words do
    collection do
      get 'words_in_day'
      get 'words_in_rss'
      get 'charts'
    end
  end

  resources :frequencies
  resources :rsses

  resources :yandex_news do
    collection do
      get 'news_category' 
    end
  end

  match "/404" => "errors#error_404", via: [ :get, :post, :patch, :delete ]
  match "/500" => "errors#error_500", via: [ :get, :post, :patch, :delete ]
  root 'search#index'

end

app/models/category_news.rb
class CategoryNews < ActiveRecord::Base
  has_many :rsses
end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
end

app/models/frequency.rb
class Frequency < ActiveRecord::Base
  has_and_belongs_to_many :words
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/rss.rb
class Rss < ActiveRecord::Base
  has_and_belongs_to_many :words
  belongs_to :category_news
end

app/models/rsses_words.rb
class RssesWords < ActiveRecord::Base
  belongs_to :word
  belongs_to :rss
end

app/models/word.rb
class Word < ActiveRecord::Base
  has_and_belongs_to_many :rsses
end

app/models/yandex_news.rb
class YandexNews < ActiveRecord::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def error_404
    redirect_to root_path
  end

  def error_500
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
#  def edit
#  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
 # def update
 #   respond_to do |format|
 #     if @post.update(post_params)
 #       format.html { redirect_to @post, notice: 'Post was successfully updated.' }
 #       format.json { render :show, status: :ok, location: @post }
 #     else
 #       format.html { render :edit }
 #       format.json { render json: @post.errors, status: :unprocessable_entity }
 #     end
 #   end
 # end

  # DELETE /posts/1
  # DELETE /posts/1.json
#  def destroy
#    @post.destroy
#    respond_to do |format|
#      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
#      format.json { head :no_content }
#    end
#  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :name)
    end
end

app/controllers/rsses_controller.rb
class RssesController < ApplicationController
  before_action :set_rss, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
  end

  def show
    @news = two_arrays_to_one(@rss.rss_index)
    #@news = @news.split(";")
    @words = @rss.words.where(date: Time.now.beginning_of_day)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rss
      @rss = Rss.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rss_params
      params.require(:rss).permit(:title, :rss_index)
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.where(date: Time.now.beginning_of_day).order("count DESC").limit(20)
    @categories = CategoryNews.all
    @time = [7,6,5,4,3,2,1,0].map{|t| Time.now.beginning_of_day - t.day}
    @words_in_dates = @time.map{|t|
      Word.where(date: t).order("count DESC").limit(20)
    }
    @rss_titles = Rss.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  def charts
    @categories = CategoryNews.all
    @time_search = params[:time] == nil ? Time.now.beginning_of_day : params[:time].to_time
    @time = [7,6,5,4,3,2,1,0].map{|t| (Time.now.beginning_of_day - t.day)}
    if params[:category_news] 
      @words_arr = Word.where(date: @time_search).joins(:rsses).where("rsses.category_news_id = #{params[:category_news]}").uniq.order("count DESC").limit(8)
    else
      @words_arr = Word.where(date: @time_search).order("count DESC").limit(8)
    end
    @words = @words_arr.map{|t| 
      result_arr = {}
      @time.each{|r|
        result_arr[r]= Word.where(title: t.title,date: r).empty? ? 0 : Word.where(title:t.title,date: r).first.count
      }
      [t.title,result_arr]
    }
    @time_date = @time.map{|t| t}
  end

  def words_in_day
    @words = Word.where(date: params[:date].to_time.beginning_of_day).order("count DESC").limit(40)
    render layout: false
  end

  def words_in_rss
    @time = [7,6,5,4,3,2,1,0].map{|t| Time.now.beginning_of_day - t.day}
    @words_in_dates = @time.map{|t|
      Word.where(date: t).joins(:rsses).where("rsses.category_news_id = #{params[:category_news_id]}").uniq.order("count DESC").limit(20)
    }
    render layout: false
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:date, :title, :count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_news_helper.rb
module CategoryNewsHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/helpers/frequencies_helper.rb
module FrequenciesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/words_helper.rb
module WordsHelper

  def d_m_y_for_date(date,class_in=nil,charts=false)
     str = "#{date.day}.#{date.month}.#{date.year}"
     class_res = class_in == nil ? "link_date" : "link_date #{class_in}"
     if charts != false
       link_to str, "/words/charts?time=#{date}#{charts == "" ? "" : "&category_news=#{charts}"}", class: class_res
     else
       link_to str, "javascript:void(0);", data: {date: date.to_s}, class: class_res
     end
  end

  def link_for_rss(rss)
     link_to rss.title, "javascript:void(0);", data: {title: rss.rss_index,id: rss.id}, class: "link_rss"
  end
end

app/helpers/yandex_news_helper.rb
module YandexNewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>SilentMouse - анализ новостей</title>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="icon" href="http://silentmouse.ru/favicon.ico" type="image/x-icon">
  <%= csrf_meta_tags %>

  <%if URI.parse(request.original_url).path.to_s == "/words" %>
    <%content_description = "SilentMouse Слова часто упоминаемые слова в новостях"%>
  <%elsif URI.parse(request.original_url).path.to_s == "/words/charts" %>
    <%content_description = "SilentMouse Графики часто упоминаемые слова в новостях анализ"%>
  <%elsif URI.parse(request.original_url).path.to_s.include? "rss"%>
    <%content_description = "SilentMouse Новости #{@rss.title}"%>
  <%else%>
    <%content_description = "SilentMouse Главная анализ новостей из сети интернет"%>
  <%end%>
  <meta content="новости, сравнение, новостей, silentmouse, big data, анализ слов, часто упоминаемые слова, слова, анализ новослей культуры, анализ новостей политики, часто упоминаемые слова в интернете, анализ интернета, графики новостей " name="keywords">
  <meta content=<%=content_description%> name="description">
</head>
<body>
<div class="nav">
  <ul>
  <li><%=link_to image_tag("logo.png"), root_path%></li>
  <li><%=link_to "Главная", yandex_news_index_path, :class=>(URI.parse(request.original_url).path.to_s == "/yandex_news" ? "active" : "nothing") %></li>
  <li><%=link_to "Анализ", root_path, :class=>(URI.parse(request.original_url).path.to_s == "/" ? "active" : "nothing") %></li>
  <li><%=link_to "Слова", words_path, :class=>(URI.parse(request.original_url).path.to_s == "/words" ? "active" : "nothing")%></li>
  <li><%=link_to "Графики", charts_words_path, :class=>(URI.parse(request.original_url).path.to_s == "/words/charts" ? "active" : "nothing")%></li>
  <li><%=link_to "Отзывы", posts_path, :class=>(URI.parse(request.original_url).path.to_s == "/posts" ? "active" : "nothing")%></li>
  </ul>
</div>
<div class="content">
<%= yield %>
</div>
<div class="footer">
  <div class="footer_center">
    &copy;
    SilentMouse
    2014 &#8211; 2015 
    <div class="pluso" data-background="#ebebeb" data-options="small,square,line,horizontal,counter,theme=04" data-services="vkontakte,odnoklassniki,facebook,twitter,google,moimir,email,print"></div>
  </div>
</div>
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter28116558 = new Ya.Metrika({id:28116558,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/28116558" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</body>
</html>